name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  arcane:
    path: ../
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  faker: ^2.2.0
  rxdart: ^0.28.0
  uuid: ^4.5.1
  fast_log: ^1.0.7
  mesh_gradient: ^1.3.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  shaders:
    - packages/arcane/resources/shaders/frost.frag
    - packages/arcane/resources/shaders/pixelate.frag
    - packages/arcane/resources/shaders/pixelate_blur.frag
    - packages/arcane/resources/shaders/rgb.frag
    - packages/arcane/resources/shaders/loader.frag
    - packages/arcane/resources/shaders/glyph.frag
    - packages/arcane/resources/shaders/invert.frag
    - packages/arcane/resources/shaders/warp.frag
    - packages/arcane/resources/shaders/black_hole.frag
    - packages/arcane/resources/shaders/lux.frag
    - packages/arcane/resources/shaders/cascade.frag
    - packages/arcane/resources/shaders/edge.frag
    - packages/arcane/resources/shaders/arcane_blur.frag
  uses-material-design: true