name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  arcane:
    path: ../
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  faker: ^2.2.0
  rxdart: ^0.28.0
  uuid: ^4.5.1
  fast_log: ^1.0.7
  mesh_gradient: ^1.3.8
  gui_shape: ^1.0.5
  soft_edge_blur: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true