name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  shadcn_flutter: any
  arcane:
    path: ../
  flutter:
    sdk: flutter
  faker: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: "GeistSans"
      fonts:
        - asset: "packages/arcane/fonts/Geist-Black.otf"
          weight: 800
        - asset: "packages/arcane/fonts/Geist-Bold.otf"
          weight: 700
        - asset: "packages/arcane/fonts/Geist-Light.otf"
          weight: 300
        - asset: "packages/arcane/fonts/Geist-Medium.otf"
          weight: 500
        - asset: "packages/arcane/fonts/Geist-SemiBold.otf"
          weight: 600
        - asset: "packages/arcane/fonts/Geist-Thin.otf"
          weight: 100
        - asset: "packages/arcane/fonts/Geist-UltraBlack.otf"
          weight: 900
        - asset: "packages/arcane/fonts/Geist-UltraLight.otf"
          weight: 200
        - asset: "packages/arcane/fonts/Geist-Regular.otf"
          weight: 400
    - family: "GeistMono"
      fonts:
        - asset: "packages/arcane/fonts/GeistMono-Black.otf"
          weight: 800
        - asset: "packages/arcane/fonts/GeistMono-Bold.otf"
          weight: 700
        - asset: "packages/arcane/fonts/GeistMono-Light.otf"
          weight: 300
        - asset: "packages/arcane/fonts/GeistMono-Medium.otf"
          weight: 500
        - asset: "packages/arcane/fonts/GeistMono-Regular.otf"
          weight: 400
        - asset: "packages/arcane/fonts/GeistMono-SemiBold.otf"
          weight: 600
        - asset: "packages/arcane/fonts/GeistMono-Thin.otf"
          weight: 100
        - asset: "packages/arcane/fonts/GeistMono-UltraBlack.otf"
          weight: 900
        - asset: "packages/arcane/fonts/GeistMono-UltraLight.otf"
          weight: 200