name: arcane
description: "A modified variant of shadcn_flutter along with new features & improvements. This package follows the changes of shadcn_flutter while also maintaining additional features & fixes."
version: 3.12.1
homepage: https://arcane.art
documentation: https://tome.arcane.art
repository: https://github.com/ArcaneArts/arcane
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cached_network_image: ">=3.0.0 <4.0.0"
  flutter_sticky_header: ">=0.7.0 <1.0.0"
  padded: ">=1.0.1 <2.0.0"
  pylon: ">=3.1.9 <4.0.0"
  rxdart: ">=0.26.0"
  sliver_tools: ">=0.2.12 <1.0.0"
  toxic: ">=1.3.2 <2.0.0"
  toxic_flutter: ">=1.1.0 <2.0.0"
  flutter_svg: ">=2.0.15 <3.0.0"
  sliver_fill_remaining_box_adapter: ">=1.0.0 <2.0.0"
  modal_bottom_sheet: ">=3.0.0 <4.0.0"
  flutter_phosphor_icons: ">=0.0.1 <0.1.0"
  ionicons: ">=0.2.2 <1.0.0"
  smooth_sheets: ">=0.10.2 <0.11.0"
  skeletonizer: ">=1.4.2 <2.0.0"
  syntax_highlight: ">=0.4.0 <0.5.0"
  country_flags: ">=3.0.0 <4.0.0"
  phonecodes: ">=0.0.3 <0.1.0"
  cross_file: ">=0.3.4 <0.4.0"
  image: ">=4.3.0 <5.0.0"
  email_validator: ">=3.0.0 <4.0.0"
  flutter_animate: ">=4.5.1 <5.0.0"
  soft_edge_blur: ">=0.1.3 <0.2.0"
  flutter_hooks: ">=0.20.5 <0.21.0"
  auto_size_text: ">=3.0.0 <4.0.0"
  flutter_thumbhash: ">=0.1.0 <0.2.0"
  octo_image: ">=2.1.0 <3.0.0"
  flutter_blurhash: ">=0.8.2 <0.9.0"
  common_svgs: ">=1.0.2 <2.0.0"
  conjure: ">=1.0.0 <2.0.0"
  data_widget: ">=0.0.2 <0.1.0"
  jiffy: ">=6.3.1 <7.0.0"
  universal_io: ">=2.2.2 <3.0.0"
  fast_log: ">=1.0.7 <2.0.0"
  desktop_drop: ">=0.5.0 <0.6.0"
  precision_stopwatch: ">=1.0.2 <2.0.0"
  font_awesome_flutter: ">=10.8.0 <11.0.0"
  meta_seo: ">=3.0.9 <4.0.0"
  uuid: ">=3.0.0 <6.0.0"
  gap: ">=3.0.0 <4.0.0"
  chat_color: ">=1.0.0 <2.0.0"
  color: ">=3.0.0 <4.0.0"
  tinycolor2: ">=3.0.1 <4.0.0"
  flutter_shaders: ">=0.1.3 <0.2.0"
  visibility_detector: ">=0.4.0 <0.5.0"
dev_dependencies:
  flutter_lints: ^5.0.0
  intl: ">=0.19.0 <0.20.0"
flutter:
  uses-material-design: true
topics:
  - widgets
  - user-interface
  - design
  - components
  - shadcn-ui
scripts:
  sync_upstream: sh ./script_sync_shadcn.sh
  hotload_docs: sh ./script_sync_docs_live.sh
  deploy_docs: sh ./script_deploy_docs_fast.sh
  validate_dependencies: dart pub global activate dependency_validator && dart pub global run dependency_validator