name: arcane
description: "Speeds up Flutter App Stuff"
version: 2.0.8
homepage: https://github.com/ArcaneArts/arcane
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  boxy: ^2.2.0
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  gap: ^3.0.1
  padded: ^1.0.1
  pylon: ^3.0.4
  rxdart: ^0.28.0
  shadcn_flutter: ^0.0.19
  sliver_tools: ^0.2.12
  tinycolor2: ^3.0.1
  toxic: ^1.3.1
  toxic_flutter: ^1.0.2+1
  page_transition: ^2.1.0
  sliver_fill_remaining_box_adapter: ^1.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_phosphor_icons: ^0.0.1+6
  ionicons: ^0.2.2
  mesh_gradient: ^1.3.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter: