name: arcane
description: "UI Components"
version: 1.0.0
homepage: https://github.com/ArcaneArts/arcane
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/geist-mono.ttf
    - family: Geist
      fonts:
        - asset: assets/fonts/geist.ttf