name: arcane
description: "Speeds up Flutter App Stuff"
version: 3.4.2
homepage: https://arcane.art
documentation: https://tome.arcane.art
repository: https://github.com/ArcaneArts/arcane
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  boxy: ^2.2.0
  flutter:
    sdk: flutter
  # https://github.com/Baseflow/flutter_cached_network_image/issues/981 
  cached_network_image: ^3.4.1 
  flutter_sticky_header: ^0.7.0
  padded: ^1.0.1 
  pylon: ^3.0.5
  rxdart: ^0.28.0
  sliver_tools: ^0.2.12
  tinycolor2: ^3.0.1
  toxic: ^1.3.2
  toxic_flutter: ^1.1.0
  flutter_svg: ^2.0.15
  page_transition: ^2.1.0
  sliver_fill_remaining_box_adapter: ^1.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_phosphor_icons: ^0.0.1+6
  ionicons: ^0.2.2
  mesh_gradient: ^1.3.8
  smooth_sheets: ^0.10.2
  pixel_snap: ^0.1.5
  file_picker: ^8.1.4
  audioplayers: ^6.1.0
  skeletonizer: ^1.4.2
  syntax_highlight: ^0.4.0
  country_flags: ^3.0.0
  phonecodes: ^0.0.3
  cross_file: ^0.3.4+2
  image: ^4.3.0
  email_validator: ^3.0.0
  flutter_animate: ^4.5.1
  soft_edge_blur: ^0.1.3
  flutter_hooks: ^0.20.5
  auto_size_text: ^3.0.0
  flutter_cache_manager: ^3.4.1
  thumbhash: ^0.1.0+1
  flutter_thumbhash: ^0.1.0+1
  octo_image: ^2.1.0
  blurhash_dart: ^1.2.1
  flutter_blurhash: ^0.8.2
  common_svgs: ^1.0.2
  conjure: ^1.0.0
  data_widget: ^0.0.2
  cupertino_icons: ^1.0.8
  jiffy: ^6.3.1
  universal_io: ^2.2.2
  date_field: ^5.3.0
  intl: ^0.19.0
  fast_log: ^1.0.7
  desktop_drop: ^0.5.0
  precision_stopwatch: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
topics:
  - widgets
  - user-interface
  - design
  - components
  - shadcn-ui